// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: github.com/dipdup-net/indexer-sdk/examples/grpc/proto/time.proto

package pb

import (
	context "context"
	pb "github.com/dipdup-net/indexer-sdk/pkg/modules/grpc/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TimeServiceClient is the client API for TimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimeServiceClient interface {
	SubscribeOnTime(ctx context.Context, in *Request, opts ...grpc.CallOption) (TimeService_SubscribeOnTimeClient, error)
	UnsubscribeFromTime(ctx context.Context, in *pb.UnsubscribeRequest, opts ...grpc.CallOption) (*pb.UnsubscribeResponse, error)
}

type timeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeServiceClient(cc grpc.ClientConnInterface) TimeServiceClient {
	return &timeServiceClient{cc}
}

func (c *timeServiceClient) SubscribeOnTime(ctx context.Context, in *Request, opts ...grpc.CallOption) (TimeService_SubscribeOnTimeClient, error) {
	stream, err := c.cc.NewStream(ctx, &TimeService_ServiceDesc.Streams[0], "/proto.TimeService/SubscribeOnTime", opts...)
	if err != nil {
		return nil, err
	}
	x := &timeServiceSubscribeOnTimeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TimeService_SubscribeOnTimeClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type timeServiceSubscribeOnTimeClient struct {
	grpc.ClientStream
}

func (x *timeServiceSubscribeOnTimeClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *timeServiceClient) UnsubscribeFromTime(ctx context.Context, in *pb.UnsubscribeRequest, opts ...grpc.CallOption) (*pb.UnsubscribeResponse, error) {
	out := new(pb.UnsubscribeResponse)
	err := c.cc.Invoke(ctx, "/proto.TimeService/UnsubscribeFromTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeServiceServer is the server API for TimeService service.
// All implementations must embed UnimplementedTimeServiceServer
// for forward compatibility
type TimeServiceServer interface {
	SubscribeOnTime(*Request, TimeService_SubscribeOnTimeServer) error
	UnsubscribeFromTime(context.Context, *pb.UnsubscribeRequest) (*pb.UnsubscribeResponse, error)
	mustEmbedUnimplementedTimeServiceServer()
}

// UnimplementedTimeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTimeServiceServer struct {
}

func (UnimplementedTimeServiceServer) SubscribeOnTime(*Request, TimeService_SubscribeOnTimeServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeOnTime not implemented")
}
func (UnimplementedTimeServiceServer) UnsubscribeFromTime(context.Context, *pb.UnsubscribeRequest) (*pb.UnsubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnsubscribeFromTime not implemented")
}
func (UnimplementedTimeServiceServer) mustEmbedUnimplementedTimeServiceServer() {}

// UnsafeTimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeServiceServer will
// result in compilation errors.
type UnsafeTimeServiceServer interface {
	mustEmbedUnimplementedTimeServiceServer()
}

func RegisterTimeServiceServer(s grpc.ServiceRegistrar, srv TimeServiceServer) {
	s.RegisterService(&TimeService_ServiceDesc, srv)
}

func _TimeService_SubscribeOnTime_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TimeServiceServer).SubscribeOnTime(m, &timeServiceSubscribeOnTimeServer{stream})
}

type TimeService_SubscribeOnTimeServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type timeServiceSubscribeOnTimeServer struct {
	grpc.ServerStream
}

func (x *timeServiceSubscribeOnTimeServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func _TimeService_UnsubscribeFromTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServiceServer).UnsubscribeFromTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TimeService/UnsubscribeFromTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServiceServer).UnsubscribeFromTime(ctx, req.(*pb.UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimeService_ServiceDesc is the grpc.ServiceDesc for TimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TimeService",
	HandlerType: (*TimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnsubscribeFromTime",
			Handler:    _TimeService_UnsubscribeFromTime_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeOnTime",
			Handler:       _TimeService_SubscribeOnTime_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/dipdup-net/indexer-sdk/examples/grpc/proto/time.proto",
}
